### ISSUE TITLE
Neil John's web page

### ISSUE THREAD

**Issue by NJ-035** [NJ-035/IPT2-CaseStudy#2]
![Main webpage](https://github.com/user-attachments/assets/ca7804ae-2f03-43c4-b048-331880b39115)

My first committed web page

@julia-julia1818 
@meg1520 
@mangel-bels

**Comment by NJ-035** [comment]
I'm done with my website and have already merged it.
@meg1520 @julia-julia1818 @mangel-bels 

![image](https://github.com/user-attachments/assets/1a0954de-d0ea-428a-a44b-716f4dfb942b)

**Comment by meg1520** [comment]
I'm done with my website and and i already megred it
![merge index](https://github.com/user-attachments/assets/e3465fca-a091-4e64-9563-8e1a4c5f89d1)

**Comment by meg1520** [comment]
this is my first merge
@NJ-035 @julia-julia1818 @mangel-bels
![31](https://github.com/user-attachments/assets/3ec589a2-9930-425a-939e-0da2396fbeef)

**Comment by NJ-035** [comment]
The web page in the main branch and my web page are now complete, and these two have also been merged.
