### ISSUE TITLE
Miguel Website

### ISSUE THREAD

**Issue by meg1520** [NJ-035/IPT2-CaseStudy#7]
My first Merge
@NJ-035 @julia-julia1818 @mangel-bels 
![31](https://github.com/user-attachments/assets/b0e2ca18-2a68-43d7-862f-22ea656b66b0)

**Comment by meg1520** [comment]
Iam done with my webpage and i already merge it to master
@NJ-035 @julia-julia1818 @mangel-bels
![merge index](https://github.com/user-attachments/assets/41a741e6-ce91-4090-805e-fd0f899ac1a2)

**Comment by NJ-035** [comment]
Your web page @meg1520 is now complete and has been merged with the main branch and/or web page.
